name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
api-version: '1.20'
commands:
  EAGuide:
    description: Gives you the plugin guide
    usage: /ElementalArtifactsGuide
  giveaxe:
    description: Gives you axe test
    usage: /giveaxe