name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
api-version: '1.20'
commands:
  EAGuide:
    description: Gives you the plugin guide
    usage: /ElementalArtifactsGuide
  giveaxe:
    description: Gives you axe test
    usage: /giveaxe
  giveportcraft:
    description: Gives you porttable test
    usage: /giveportcraft
  givedoublesword:
    description: Gives you doublesword test
    usage: /givedoubledword
  givewarpsword:
    description: Gives Warp Sword test
    usage: /givewarpsword
  bookofitems:
    description: Gives the book of items. ONLY FOR ADMINS!
    usage: /bookpfitems
  givebindingarmor:
    description: Gives binding armor test
    usage: /givebindingarmor
  givefearmongerpearl:
    description: Gives you a fear mongerer pearl.
    usage: /givefearmongerpearl