name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
api-version: '1.20'
commands:
  EA:
    description: Gives you the recipe book
    usage: /elementalartifacts