name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
softdepend: [Citizens]
api-version: '1.20'
commands:
  EAGuide:
    description: Gives you the plugin guide
    usage: /ElementalArtifactsGuide
  GivePlasmaPick_1:
    description: Gives Plasma Pick t1
    usage: /giveplasmapick_1
  GiveStarDustCH:
    description: Gives star dust mining tool
    usage: /givestardustmine_1