name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
api-version: '1.20'
commands:
  givebook1:
    description: Gives you the plugin guide
    usage: /ElementalArtifactsGuide
    aliases: /EAG
  giveaxe:
    description: Gives you axe test
    usage: /giveaxe