name: ElementalArtifacts
version: '${project.version}'
main: org.elemental.ElementalArtifacts
api-version: '1.20'
commands:
  givebook:
    description: Gives you the recipe book
    usage: /givebook
  giveaxe:
    description: Gives you axe test
    usage: /ElementalArtifacts
    aliases: /EA